import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { TRPCReactProvider } from "~/trpc/react";
import { Toaster } from "~/components/ui/toaster";
import NavigationBarCraddle from "~/components/navigationBar/NavigationBarCraddle";

export const metadata: Metadata = {
  title: "Harmony",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <NavigationBarCraddle />
          {children}
          <Toaster />
        </TRPCReactProvider>
      </body>
    </html>
  );
}